name: Submit Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: github.repository == 'mikesilvo164/script.skinshortcuts'

    name: Submit Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Add-on
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/romanvm/kodi-addon-submitter.git

      - name: Configure git
        run: |
          git config --global user.name "mikesilvo164"
          git config --global user.email "mikesilvo164@users.noreply.github.com"

      - name: Remove Unwanted Files
        run: |
          mv .git ..
          rm -rf .??*
          mv ../.git .
          rm -f LICENSE.txt
          rm -f README.md
          rm -rf docs/
          rm -rf tests/
          rm -rf typings/
          rm -f pyrightconfig.json
          rm -f ruff.toml
          git add .
          git commit -m "Remove unwanted files"
        working-directory: ${{ github.event.repository.name }}

      - name: Submit to Official Repository
        id: submit
        run: |
          submit-addon -r repo-scripts -b omega --pull-request ${{ github.event.repository.name }}
        working-directory: ${{ github.event.repository.name }}
        env:
          GH_USERNAME: mikesilvo164
          GH_TOKEN: ${{ secrets.ADDON_SUBMISSION_TOKEN }}
          EMAIL: mikesilvo164@users.noreply.github.com
